# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('basevalue', models.PositiveIntegerField()),
                ('player_type', models.CharField(choices=[('BA', 'Batsman'), ('BO', 'Bowler'), ('WK', 'Wicket Keeper'), ('AR', 'All Rounder')], default='BA', max_length=2)),
                ('nationality', models.CharField(choices=[('IN', 'Indian'), ('FO', 'Foreigner')], default='IN', max_length=2)),
            ],
        ),
    ]
