# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='owner',
            field=models.CharField(default='Unsold', max_length=100),
        ),
    ]
