# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_player_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owner',
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(default='NUL', max_length=3),
        ),
    ]
