# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170313_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='remaining_cash',
            field=models.PositiveIntegerField(default=3500),
        ),
    ]
