# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_owner_remaining_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='basevalue',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
