# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170313_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='points',
            new_name='Points',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='remaining_cash',
            new_name='Remaining_cash',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='team_name',
            new_name='Team_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='basevalue',
            new_name='Basevalue',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nationality',
            new_name='Nationality',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='pid',
            new_name='Pid',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_type',
            new_name='Player_type',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_name',
            new_name='Team_name',
        ),
    ]
