# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170313_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='Is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
