# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Match_id',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
