# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_match_match_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
