# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_team_player',
            fields=[
                ('Pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Runs', models.PositiveIntegerField(default=0)),
                ('Balls_faced', models.PositiveIntegerField(default=0)),
                ('Fours', models.PositiveIntegerField(default=0)),
                ('Sixes', models.PositiveIntegerField(default=0)),
                ('Strike_rate', models.PositiveIntegerField(default=0)),
                ('Overs', models.PositiveIntegerField(default=0)),
                ('Maiden_overs', models.PositiveIntegerField(default=0)),
                ('Runs_given', models.PositiveIntegerField(default=0)),
                ('Wickets', models.PositiveIntegerField(default=0)),
                ('No_balls', models.PositiveIntegerField(default=0)),
                ('Wide_balls', models.PositiveIntegerField(default=0)),
                ('Economy', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_id', models.CharField(default='0', max_length=20)),
                ('Current_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.In_team_player')),
            ],
        ),
    ]
