# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_in_team_player_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='Current_player',
        ),
        migrations.AddField(
            model_name='player',
            name='Points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='In_team_player',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
