# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170319_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Is_captain',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Is_playing',
            field=models.BooleanField(default=True),
        ),
    ]
